[package]
name = "box-with-tri-hole"
version = "0.1.0"
edition = "2024"

[dependencies]
fj = { git = "https://github.com/winksaville/fornjot", branch = "dep-box-with-tri-hole" }

[profile.release]
incremental = false
codegen-units = 1

[profile.dev]
incremental = true
codegen-units = 16
